name: Build and Push Dist

on:
  push:
    branches-ignore:
      - main # This will exclude the 'main' branch
    paths-ignore:
      - "dist/**"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Change if you're using a different Node.js version

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run TSUP to Build
        run: npx tsup

      - name: Check for Changes in Dist
        id: dist-check
        run: |
          git diff --exit-code dist
        continue-on-error: true

      - name: Commit and Push Dist Folder
        if: steps.dist-check.outcome == 'failure' # Run only if 'git diff' found changes (exit code 1)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@cloudgeometry.com"
          git add dist
          git commit -m 'chore: update dist folder [skip ci]' || echo "No changes to commit"
          git push

      - name: Done
        run: echo "Build and push completed!"
